import Head from "next/head";
import NavBar from "@/Components/NavBar";
import HomeMain from "@/Components/Home/HomeMain";
import { useEffect } from "react";

export default function Home() {
  let responseData = undefined;
  useEffect(() => {
    const fetchData = async () => {
      // AIzaSyB5ZH2gxc5TlMhav11Btl9XSX-iTyXyI4w
      try {
        responseData = await fetch(
          "http://api.openweathermap.org/geo/1.0/direct?q=London&limit=5&appid={e630fe3f07e332b41351ba46c4dd1997}"
        );
      } catch (err) {
        console.log(err);
      }
    };
    fetchData();
  }, [responseData]);

  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav
        style={{
          background: "rgba(114, 113, 113, 0.75)",
          borderBottomLeftRadius: "35px",
          borderBottomRightRadius: "35px",
          position: "sticky",
          top: 0,
        }}
      >
        <NavBar />
      </nav>
      <main>
        <HomeMain />
      </main>
    </>
  );
}
