import React, { useEffect, useState, useContext } from "react";
import NavBar from "../NavBar";

import Head from "next/head";

import styles from "../../styles/card.module.css";

import CardMain from "../Card/CardMain";

import { AuthContext } from "../AuthContext";

import { useHttpClient } from "../httpHooks";

import { ColorRing } from "react-loader-spinner";
import Link from "next/link";

function MyPostMain() {
  const [userPlaces, setUserPlaces] = useState(false);

  const auth = useContext(AuthContext);

  const { sendRequest, isLoading } = useHttpClient();

  const userId = auth.userId;

  useEffect(() => {
    const fetchPlace = async () => {
      try {
        const responseData = await sendRequest(
          `http://localhost:5000/api/places/user/${userId}`
        );
        setUserPlaces(responseData.places);
        console.log(userPlaces);
      } catch (err) {}
    };
    fetchPlace();
  }, [sendRequest, userId]);

  return (
    <>
      <Head>
        <title>My Post</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav
        style={{
          background: "rgba(114, 113, 113, 0.75)",
          borderBottomLeftRadius: "35px",
          borderBottomRightRadius: "35px",
          position: "sticky",
          top: 0,
        }}
      >
        <NavBar />
      </nav>
      {isLoading && (
        <div
          style={{
            position: "fixed",
            top: "40vh",
            left: "80vh",
          }}
        >
          <ColorRing
            visible={true}
            height="200"
            width="200"
            ariaLabel="blocks-loading"
            wrapperStyle={{}}
            wrapperClass="blocks-wrapper"
            colors={["#f59547", "#f55347", "#54b53c", "#3c80b5", "#9a45d6"]}
          />
        </div>
      )}
      {!userPlaces && (
        <div className={styles.noPlace}>
          <h1>No Place Found</h1>
          <Link style={{ all: "unset", cursor: "pointer" }} href="/createpost">
            <h2
              style={{
                marginTop: "5vh",
                marginLeft: "0vh",
                backgroundColor: "GrayText",
                width: "65vh",
                height: "20vh",
                borderRadius: "20px",
                paddingLeft: "20px",
                textAlign: "center",
                paddingTop: "8vh",
              }}
            >
              Click to create one ?
            </h2>
          </Link>
        </div>
      )}
      <div style={{ marginLeft: "35vh", marginTop: "5vh" }}>
        {userPlaces &&
          userPlaces.map((place) => (
            <CardMain
              pid={place.id}
              user={place.user}
              title={place.title}
              desc={place.desc}
              img={place.img}
              lat={place.lat}
              long={place.lon}
            />
          ))}
      </div>
    </>
  );
}

export default MyPostMain;
