import React, { useState, useEffect } from "react";
import Head from "next/head";
import NavBar from "@/Components/NavBar";

import CardMain from "@/Components/Card/CardMain";

import styles from "../../styles/card.module.css";

import { useRouter } from "next/router";
import { useHttpClient } from "@/Components/httpHooks";

function UserPost() {
  const router = useRouter();

  const [userPlace, setUserPlaces] = useState();

  const { sendRequest } = useHttpClient();

  const pid = router.query.pid;
  useEffect(() => {
    const fetchPlace = async () => {
      try {
        const responseData = await sendRequest(
          `http://localhost:5000/api/places/user/${pid}`
        );
        console.log(responseData.places);
        setUserPlaces(responseData.places);
      } catch (err) {}
    };
    fetchPlace();
  }, [sendRequest, pid]);

  return (
    <>
      <Head>
        <title>User Post</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav
        style={{
          background: "rgba(114, 113, 113, 0.75)",
          borderBottomLeftRadius: "35px",
          borderBottomRightRadius: "35px",
          position: "sticky",
          top: 0,
        }}
      >
        <NavBar />
      </nav>
      <div>
        {!userPlace && (
          <div className={styles.noPlace}>
            <h1>No Place Found</h1>
          </div>
        )}
        <div style={{ marginLeft: "35vh", marginTop: "5vh" }}>
          {userPlace &&
            userPlace.map((place) => (
              <CardMain
                pid={place.id}
                user={place.user}
                title={place.title}
                desc={place.desc}
                img={place.img}
                lat={place.lat}
                long={place.lon}
              />
            ))}
        </div>
      </div>
    </>
  );
}

export default UserPost;
